# Generated by Django 4.1.7 on 2023-03-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CardTransactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("series_reference", models.CharField(max_length=255)),
                ("period", models.CharField(blank=True, max_length=255, null=True)),
                ("data_value", models.FloatField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
                ("units", models.CharField(blank=True, max_length=255, null=True)),
                ("magnitude", models.IntegerField(blank=True, null=True)),
                ("subject", models.CharField(blank=True, max_length=255, null=True)),
                ("group", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "series_title_1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "series_title_2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
    ]
